### ISSUE TITLE
ERROR: MicrosoftAzureStorage - Error occurred while uploading to Azure

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-storage-plugin#173]
<p>Hi,</p>

<p>Using the following environment versions:</p>

<p>Jenkins 2.222.1<br/>
 Windows Azure Storage: 1.1.5</p>

<p> </p>

<p>It happens from time to time (not always), which is problematic for the builds health. The following error:</p>

```text
MicrosoftAzureStorage - Container name: results-artifacts
MicrosoftAzureStorage - share name:
MicrosoftAzureStorage - File path: **/reports/*.xml
MicrosoftAzureStorage - Virtual path: (removed by me)
MicrosoftAzureStorage - Exclude path:
MicrosoftAzureStorage - Uploading files to Microsoft Azure
MicrosoftAzureStorage - Need uploaded/archived file count = 2
ERROR: MicrosoftAzureStorage - Error occurred while uploading to Azure - (removed by me)
com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Only 0/2 files are successfully uploaded.
at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.execute(UploadService.java:736)
at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:438)
at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Shell Script (self time 893ms)
```

<p>In these failed attempts, there was an inconsistency, in a way that sometimes the artefacts were even found in the blob, and sometimes not found.</p>

<p> </p>

<p>Would be helpful to also get a more verbose error message from MS REST API response that we can traceback and debug. Since </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">error code 0</pre>
</div></div>
<p>does not indicate the exact problem.</p>

<p> </p>

<p>Thank you.</p>

<p> </p>
<i>[JENKINS-64128] created by mfarahat_kg</i>

**Comment by HeidiRechek** [comment]
I have same issue: 
Jenkins 2.277.1
Azure Commons (just updated today to) 1.1.2
Windows Azure Storage plugin 1.1.7

**Comment by timja** [comment]
You don't happen to have a stack trace that is formatted better than the above one @HeidiRechek ?

**Comment by HeidiRechek** [comment]
hows this: 
MicrosoftAzureStorage - Container name: results-artifacts
MicrosoftAzureStorage - share name: 
MicrosoftAzureStorage - File path: **/reports/*.xml
MicrosoftAzureStorage - Virtual path: <removed by me>
MicrosoftAzureStorage - Exclude path: 
MicrosoftAzureStorage - Uploading files to Microsoft Azure
MicrosoftAzureStorage - Need uploaded/archived file count = 2
ERROR: MicrosoftAzureStorage - Error occurred while uploading to Azure - <removed by me>
com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Only 0/2 files are successfully uploaded.
	at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.execute(UploadService.java:736)
	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:438)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
 Shell Script (self time 893ms)

**Comment by timja** [comment]
Probably needs an SDK upgrade and some resiliency added if the SDK upgrade doesn't add that.

From what I remember the SDK here is ancient

**Comment by HeidiRechek** [comment]
Will you be upgrading the SDK and adding resilency? I do not have the knowledge for that.

**Comment by timja** [comment]
at some point, not right now

**Comment by timja** [comment]
Upgraded now @HeidiRechek, this issue should be fixed in https://github.com/jenkinsci/azure-storage-plugin/releases/tag/354.vc32740f0e225
