### ISSUE TITLE
Only X-1/X files are successfully uploaded

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-storage-plugin#176]
<p>When uploading our artifacts to storage, we have been seeing sometimes that one file will fail to upload randomly which causes the plugin to throw and ends up failing the build.  </p>

<p>The files are all under the 100mb limit so we aren't hitting the payload size limit for a single file.  I don't see any specific error related to the why one of the files failed to upload, only the summary that shows one of the files that didn't upload successfully. </p>

<p>Is there somewhere else to check to find why the upload failed?</p>

<p>Also it would be nice if there was an option to retry the upload rather than fail the build.</p>

<p> </p>

<p>Here's the console log error:</p>

```text
MicrosoftAzureStorage - Container name: artifactsMicrosoftAzureStorage - Container name: artifactsMicrosoftAzureStorage - share name: MicrosoftAzureStorage - File path: **\*.png, fingerPrint.txt,TestResults/*.xml, **\*.trx, **\*.logMicrosoftAzureStorage - Virtual path: MicrosoftAzureStorage - Exclude path: MicrosoftAzureStorage - Uploading files to Microsoft AzureUploaded to file storage with uri https:<span class="code-comment">//[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/11/TestResults/EditableGridValidation-2019-12-23_11-35-37-9.png in 00:00:00.073 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/11/TestResults/GridEditableSanity-2019-12-23_11-39-20-1.png in 00:00:00.166 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/15/TestResults/AMDMultiSelectDropDownSanity-2019-12-23_11-34-54-3.png in 00:00:00.311 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/15/TestResults/EssentialsSanity-2019-12-23_11-35-11-4.png in 00:00:00.366 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/15/TestResults/EssentialsSanity-2019-12-23_11-37-07-0.png in 00:00:00.404 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/1/TestResults/AMDDropDownSanity-2019-12-23_11-35-25-7.png in 00:00:00.476 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/1/TestResults/AMDDropDownSanity-2019-12-23_11-36-59-6.png in 00:00:00.516 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/7/TestResults/ToolbarSanityV2-2019-12-23_11-33-02-4.png in 00:00:00.608 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/9/TestResults/HotspotSanity-2019-12-23_11-35-37-5.png in 00:00:00.657 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/9/TestResults/HotspotSanity-2019-12-23_11-36-35-5.png in 00:00:00.698 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/10/TestResults/[REMOVED]_[REMOVED]116%202019-12-23%2011_32_47.trx in 00:00:00.069 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/11/TestResults/[REMOVED]_[REMOVED]503%202019-12-23%2011_32_56.trx in 00:00:00.152 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/11/TestResults/[REMOVED]_[REMOVED]503%202019-12-23%2011_32_56_ORIGINAL.trx in 00:00:00.136 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/11/TestResults/[REMOVED]_[REMOVED]503%202019-12-23%2011_32_56_RETRY_1.trx in 00:00:00.168 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/12/TestResults/[REMOVED]_[REMOVED]251%202019-12-23%2011_32_46.trx in 00:00:00.219 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/13/TestResults/[REMOVED]_[REMOVED]132%202019-12-23%2011_32_46.trx in 00:00:00.234 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/14/TestResults/[REMOVED]_[REMOVED]323%202019-12-23%2011_32_56.trx in 00:00:00.350 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/15/TestResults/[REMOVED]_[REMOVED]550%202019-12-23%2011_32_43.trx in 00:00:00.422 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/15/TestResults/[REMOVED]_[REMOVED]550%202019-12-23%2011_32_43_ORIGINAL.trx in 00:00:00.450 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/15/TestResults/[REMOVED]_[REMOVED]550%202019-12-23%2011_32_43_RETRY_1.trx in 00:00:00.452 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/1/TestResults/[REMOVED]_[REMOVED]177%202019-12-23%2011_32_41.trx in 00:00:00.515 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/1/TestResults/[REMOVED]_[REMOVED]177%202019-12-23%2011_32_41_ORIGINAL.trx in 00:00:00.515 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/1/TestResults/[REMOVED]_[REMOVED]177%202019-12-23%2011_32_41_RETRY_1.trx in 00:00:00.546 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/2/TestResults/[REMOVED]_[REMOVED]086%202019-12-23%2011_33_30.trx in 00:00:00.613 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/3/TestResults/[REMOVED]_[REMOVED]092%202019-12-23%2011_33_37.trx in 00:00:00.655 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/4/TestResults/[REMOVED]_[REMOVED]104%202019-12-23%2011_32_31.trx in 00:00:00.665 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/5/TestResults/[REMOVED]_[REMOVED]071%202019-12-23%2011_32_38.trx in 00:00:00.640 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/6/TestResults/[REMOVED]_[REMOVED]240%202019-12-23%2011_32_57.trx in 00:00:00.599 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/7/TestResults/[REMOVED]_[REMOVED]535%202019-12-23%2011_32_50.trx in 00:00:00.267 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/7/TestResults/[REMOVED]_[REMOVED]535%202019-12-23%2011_32_50_ORIGINAL.trx in 00:00:00.123 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/7/TestResults/[REMOVED]_[REMOVED]535%202019-12-23%2011_37_01.trx in 00:00:00.071 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/8/TestResults/[REMOVED]_[REMOVED]368%202019-12-23%2011_33_02.trx in 00:00:00.518 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/9/TestResults/[REMOVED]_[REMOVED]388%202019-12-23%2011_32_46.trx in 00:00:00.053 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/9/TestResults/[REMOVED]_[REMOVED]388%202019-12-23%2011_32_46_ORIGINAL.trx in 00:00:00.085 (HH:mm:ss.S)Uploaded to file storage with uri https://[REMOVED].blob.core.windows.net/artifacts/test-splits/reports/9/TestResults/[REMOVED]_[REMOVED]388%202019-12-23%2011_32_46_RETRY_1.trx in 00:00:00.039 (HH:mm:ss.S)MicrosoftAzureStorage - Need uploaded/archived file count = 36ERROR: MicrosoftAzureStorage - Error occurred <span class="code-keyword">while</span> uploading to Azure - [REMOVED]com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Only 35/36 files are successfully uploaded. at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.execute(UploadService.java:729) at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:438) at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79) at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32) at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741) at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690) at hudson.model.Build$BuildExecution.post2(Build.java:186) at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635) at hudson.model.Run.execute(Run.java:1840) at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43) at hudson.model.ResourceController.execute(ResourceController.java:97) at hudson.model.Executor.run(Executor.java:429)ERROR: Step ï¿½Upload artifacts to Microsoft Azure Storageï¿½ aborted due to exception: java.io.IOException: MicrosoftAzureStorage - Error occurred <span class="code-keyword">while</span> uploading to Azure - [REMOVED] at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:469) at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79) at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32) at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741) at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690) at hudson.model.Build$BuildExecution.post2(Build.java:186) at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635) at hudson.model.Run.execute(Run.java:1840) at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43) at hudson.model.ResourceController.execute(ResourceController.java:97) at hudson.model.Executor.run(Executor.java:429)
```

<i>[JENKINS-60576] created by rpwong</i>

**Comment by timja** [comment]
duplicate of https://github.com/jenkinsci/azure-storage-plugin/issues/176
