### ISSUE TITLE
Failing with Azure Stack

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-storage-plugin#179]
<p>Moved from github.</p>

<p>charliejllewellyn:</p>

<p>Hi I am trying to use this with Azure Stack. It is failing with:Hi I am trying to use this with Azure Stack. It is failing with:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Failed to validate storage account details. Please verify storage account name and key. If you are using a <span class="code-keyword">private</span> or other Windows Azure cloud service, make sure that the blob endpoint url is correct.Storage Account name -->jenkinsupload<--Blob end point url --->https:<span class="code-comment">//jenkinsupload.blob.local.azurestack.external/<---ERROR: Step ‘Upload artifacts to Microsoft Azure Storage’ aborted due to exception: java.io.IOException: Plugin can not <span class="code-keyword">continue</span>, until previous errors are addressed at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:403) at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78) at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32) at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779) at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720) at hudson.model.Build$BuildExecution.post2(Build.java:186) at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665) at hudson.model.Run.execute(Run.java:1753) at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43) at hudson.model.ResourceController.execute(ResourceController.java:98) at hudson.model.Executor.run(Executor.java:405)</span>
</pre>
</div></div>

<p> This could be for many reasons, SSL verification (although I have added the root cert to the java keystore), incorrect API versions, or incorrect resource provided in the token request. <br/>
 How can I enable debug logging and where should I look to troubleshoot this please.</p>

<p> </p>

<p>juniwang:</p>

<p>Unfortunately we haven't tested the plugin in Azure Stack nor exposed the underlying exception. Might be better to verbose the underlying exception for debuging in next release.</p>

<p>For now, it's really hard to find the root cause. But at my first sight, your blob endpoint Url <a href="https://jenkinsupload.blob.local.azurestack.external/" class="external-link" target="_blank" rel="nofollow noopener">https://jenkinsupload.blob.local.azurestack.external/</a> is beyond our expect. See <a href="https://github.com/jenkinsci/windows-azure-storage-plugin/blob/dev/src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java#L199" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/windows-azure-storage-plugin/blob/dev/src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java#L199</a>. We tried to parse the endpoint suffix by finding substring `core` in the url. That means in your case, you didn't even try to connect to your AzureStack.</p>

<p>If it's possible, could you please try to build and debug the plugin on your side? Sure we can do some fixes about logs/endpoints but it's hard for us to validate it since we don't have a AzureStack instance.</p>

<p> </p>
<i>[JENKINS-55633] created by jieshe</i>

**Comment by timja** [comment]
I'm going to close this as there has been some improvements around here and I have no way to validate it, but if someone comes along who can test pre-release builds then we can take a look at it
