### ISSUE TITLE
AzureStorage - Uploading files to Azure ERROR 

### ISSUE THREAD

**Issue by mkryptis** [jenkinsci/azure-storage-plugin#199]
### Version report

Jenkins and plugins versions report:

```
361.vfd353ee551ee
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Windows Jenkins pipeline
```

### Reproduction steps

                                azureUpload fileShareName: 'XXXXX',
                                    filesPath: "tmp/*.txt",
                                    storageCredentialId: 'YYYYYYYYYYY',
                                    storageType: 'filestorage',
                                    uploadArtifactsOnlyIfSuccessful: true,
                                    doNotFailIfArchivingReturnsNothing: true,
                                    virtualPath: 'testUpload',
                                    verbose: true

### Results

Expected result:

expected was file uploaded to azure file share

Actual result:

AzureStorage - Uploading files to Azure
ERROR: AzureStorage - Error occurred while downloading from Azure - XXXXX:Failed uploading file
com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Failed uploading file
	at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.uploadCloudFile(UploadService.java:579)
	at com.microsoftopentechnologies.windowsazurestorage.service.UploadService$FileUploadThread.run(UploadService.java:119)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: D:\Temp\tmp\aaaa.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.uploadCloudFile(UploadService.java:567)

**Comment by timja** [comment]
Please provide full plugin and jenkins report, is it failing all the time or was this a one off?

**Comment by mkryptis** [comment]
upload fails always for 2 latest plugin versions installed on jenkins.
The interesting thing is that the directory tree is created fine in azure file share, but not the files uploaded.

The last version it was working fine was: 358.v5c001416d74f

**Comment by timja** [comment]
Can't reproduce =/.

**Comment by mkryptis** [comment]
jenkins core upgrade to didn't help:
Jenkins: 2.314
OS: Linux - 5.8.0-1040-azure

**Comment by timja** [comment]
And it works if you downgrade just azure storage?

**Comment by asthomasdk** [comment]
I work with @mkryptis  on this setup with one of our customers. 

We have been having this problem for a while now, and have basically held back on upgrading this plugin since the error first started occuring in version 3.51 (I think it was). 

The problem is ocurring on pipelines that have not been changed at all - so the only change is the plugin version. For some reason the updated plugin cannot find files that we know are available in the pipeline workspace - as we can read them from groovy code prior to using the plugin. 

Downgrading just the azure storage plugin makes it work again.

**Comment by timja** [comment]
Try this then (on newer then 2.306): https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/jackson2-api/2.12.5-rc208.8a13e6539d2e/jackson2-api-2.12.5-rc208.8a13e6539d2e.hpi

Context: https://github.com/jenkinsci/azure-storage-plugin/issues/188#issuecomment-921618320

**Comment by mkryptis** [comment]
Updated junkins plugins to latest versions - that didn't help either

Jenkins: 2.314
OS: Linux - 5.8.0-1041-azure
---
Office-365-Connector:4.15.2
ace-editor:1.1
active-directory:2.25
adoptopenjdk:1.4
ant:1.12
antisamy-markup-formatter:2.1
apache-httpcomponents-client-4-api:4.5.13-1.0
atlassian-jira-software-cloud:1.4.4
authentication-tokens:1.4
aws-credentials:1.32
aws-java-sdk:1.12.70
aws-java-sdk-cloudformation:1.12.70
aws-java-sdk-codebuild:1.12.70
aws-java-sdk-ec2:1.12.70
aws-java-sdk-ecr:1.12.70
aws-java-sdk-ecs:1.12.70
aws-java-sdk-elasticbeanstalk:1.12.70
aws-java-sdk-iam:1.12.70
aws-java-sdk-logs:1.12.70
aws-java-sdk-minimal:1.12.70
aws-java-sdk-ssm:1.12.70
azure-artifact-manager:94.vcb8b76839313
azure-commons:1.1.3
azure-credentials:190.v059127ae17bb
azure-sdk:48.veb7555463c4b
badge:1.8
bitbucket:1.1.29
bitbucket-build-status-notifier:1.4.2
blueocean:1.25.0
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.0
blueocean-commons:1.25.0
blueocean-config:1.25.0
blueocean-core-js:1.25.0
blueocean-dashboard:1.25.0
blueocean-display-url:2.4.1
blueocean-events:1.25.0
blueocean-git-pipeline:1.25.0
blueocean-github-pipeline:1.25.0
blueocean-i18n:1.25.0
blueocean-jira:1.25.0
blueocean-jwt:1.25.0
blueocean-personalization:1.25.0
blueocean-pipeline-api-impl:1.25.0
blueocean-pipeline-editor:1.25.0
blueocean-pipeline-scm-api:1.25.0
blueocean-rest:1.25.0
blueocean-rest-impl:1.25.0
blueocean-web:1.25.0
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.1-1
bouncycastle-api:2.25
branch-api:2.7.0
build-name-setter:2.2.0
build-pipeline-plugin:1.5.8
build-timeout:1.20
build-timestamp:1.0.3
built-on-column:1.1
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:2.9.11
cloudbees-folder:6.16
command-launcher:1.6
conditional-buildstep:1.4.1
config-file-provider:3.8.1
configuration-as-code:1.54
configuration-as-code-groovy:1.1
convert-to-pipeline:1.0
copyartifact:1.46.2
credentials:2.6.1
credentials-binding:1.27
dashboard-view:2.17
display-url-api:2.3.5
docker-commons:1.17
docker-workflow:1.26
durable-task:1.39
echarts-api:5.2.1-2
email-ext:2.83
envinject:2.4.0
envinject-api:1.7
extended-choice-parameter:0.82
extensible-choice-parameter:1.8.0
external-monitor-job:1.7
favorite:2.3.3
file-operations:1.11
font-awesome-api:5.15.4-1
fstrigger:0.41
git:4.8.2
git-client:3.10.0
git-server:1.10
github:1.34.1
github-api:1.133
github-branch-source:2.11.3
gitlab-plugin:1.5.20
global-slack-notifier:1.5
google-metadata-plugin:0.3.1
google-oauth-plugin:1.0.6
google-storage-plugin:1.5.4
gradle:1.37.1
greenballs:1.15.1
groovy-postbuild:2.5
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.26
http_request:1.11
jackson2-api:2.13.0-226.v0c5dd2d2fd2a
javadoc:1.6
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.0
jenkins-jira-issue-updater:1.18
jenkins-multijob-plugin:1.36
jira:3.6
jira-ext:0.9
jira-steps:1.6.0
jira-trigger:1.0.1
jjwt-api:0.11.2-9.c8b45b8bb173
job-dsl:1.77
jobcacher:1.0
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
ldap:2.7
lockable-resources:2.11
log-parser:2.1
mailer:1.34
mapdb-api:1.0.9.0
matrix-auth:2.6.8
matrix-project:1.19
maven-plugin:3.13
mercurial:2.15
momentjs:1.1.1
msbuild:1.30
mstestrunner:1.3.0
multiple-scms:0.8
nodejs:1.4.0
nodelabelparameter:1.9.2
oauth-credentials:0.4
okhttp-api:3.14.9
pam-auth:1.6
parameterized-trigger:2.41
periodicbackup:1.6
pipeline-build-step:2.15
pipeline-github-lib:1.0
pipeline-graph-analysis:1.11
pipeline-input-step:2.12
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.2
pipeline-model-definition:1.9.2
pipeline-model-extensions:1.9.2
pipeline-npm:0.9.2
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.9.2
pipeline-stage-view:2.19
pipeline-utility-steps:2.10.0
plain-credentials:1.7
plugin-util-api:2.5.0
popper-api:1.16.1-2
popper2-api:2.10.2-1
postbuild-task:1.9
powershell:1.6
pubsub-light:1.16
resource-disposer:0.16
role-strategy:3.2.0
run-condition:1.5
saferestart:0.3
scm-api:2.6.5
script-security:1.78
slack:2.48
slave-setup:1.10
slave-status:1.6
snakeyaml-api:1.29.1
sonar:2.13.1
sonar-quality-gates:1.3.1
sse-gateway:1.24
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:1.23
subversion:2.14.5
thinBackup:1.10
timestamper:1.13
token-macro:266.v44a80cf277fd
tool-labels-plugin:3.0
trilead-api:1.0.13
variant:1.4
versionnumber:1.9
webhook-step:1.4
windows-azure-storage:361.vfd353ee551ee
windows-slaves:1.8
wix:1.12
workflow-aggregator:2.6
workflow-api:2.46
workflow-basic-steps:2.24
workflow-cps:2.94
workflow-cps-global-lib:2.21
workflow-durable-task-step:2.40
workflow-job:2.41
workflow-multibranch:2.26
workflow-scm-step:2.13
workflow-step-api:2.24
workflow-support:3.8
ws-cleanup:0.39

**Comment by mkryptis** [comment]
the groovy code to upload file:

azureUpload fileShareName: 'FileShareName',
                            filesPath: "${uploadFile}",
                            storageCredentialId: 'CredentialsId',
                            storageType: 'filestorage',
                            uploadArtifactsOnlyIfSuccessful: true,
                            doNotFailIfArchivingReturnsNothing: true,
                            virtualPath: "VirtualPath",
                            verbose: true

**Comment by mkryptis** [comment]
With that configuration still same error we have (it says error while downloading, but it does uploading):

ERROR: AzureStorage - Error occurred while downloading from Azure - pmcuser:Failed uploading file
com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Failed uploading file
	at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.uploadCloudFile(UploadService.java:579)
	at com.microsoftopentechnologies.windowsazurestorage.service.UploadService$FileUploadThread.run(UploadService.java:119)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: C:\Jenkins\workspace\TestAzureFileUpload\buildenv.test.props (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)

And the file C:\Jenkins\workspace\TestAzureFileUpload\buildenv.test.props is for sure in right location on disk (it's contents can be viewed in the pipeline just before the azureUpload plugin starts its action).

Any ideas to look at?

**Comment by timja** [comment]
It would be yes but I don't have an example for that

**Comment by timja** [comment]
Is this 100% reproducible or only some times?

If reproducible can someone come up with a minimum pipeline script that reproduces it consistently?

**Comment by asthomasdk** [comment]
We get it all the time if we upgrade to the latest. 
I just reverted from 361.vfd353ee551ee, which I had upgraded to today and back to 351.v1aa8afb7af77 - and the errors go away.  

I can put together a simple pipeline that shows the error and post this.

**Comment by timja** [comment]
If you can give something that can reliably reproduce it with the latest Jenkins core weekly, this plugin and jackson2-api that would be great.

**Comment by timja** [comment]
Thanks I've reproduced it

**Comment by timja** [comment]
Looks like it's a bug with File storage and agents, blob storage works fine.

My previous testing had the controller and agent on the same machine which works just fine 😢.
Starting an agent in docker was enough to reproduce this.

**Comment by asthomasdk** [comment]
Good you were able to reproduce... We've spent ages trying to work out of we had done something wrong in our setup and also look at alternatives such as the az cli, which is no where close.

**Comment by timja** [comment]
I’ll have a fix up in the next few days as I have time, it’s a fairly easy fix

**Comment by timja** [comment]
Can you please try https://github.com/jenkinsci/azure-storage-plugin/releases/tag/362.v15e9c092bf7c

**Comment by timja** [comment]
Could you try reduce that error down to a reproducible case?

**Comment by HeidiRechek** [comment]
here is the log entry from logger://com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher

  log_thrown: com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Failed to validate storage account details. Please verify storage account name and key. If you are using a private or other Azure cloud service, make sure that the blob endpoint url is correct.
	at com.microsoftopentechnologies.windowsazurestorage.helper.AzureUtils.validateStorageAccount(AzureUtils.java:74)
	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.validateData(WAStoragePublisher.java:567)
	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:437)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: reactor.core.Exceptions$ReactiveException: java.io.IOException: An existing connection was forcibly closed by the remote host
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
	at com.azure.storage.blob.BlobContainerClient.existsWithResponse(BlobContainerClient.java:228)
	at com.azure.storage.blob.BlobContainerClient.exists(BlobContainerClient.java:211)
	at com.microsoftopentechnologies.windowsazurestorage.helper.AzureUtils.getBlobContainerReference(AzureUtils.java:127)
	at com.microsoftopentechnologies.windowsazurestorage.helper.AzureUtils.validateStorageAccount(AzureUtils.java:69)
	... 10 more
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 16 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

   message: Failed to validate storage account details. Please verify storage account name and key. If you are using a private or other Azure cloud service, make sure that the blob endpoint url is correct.
   thread_id: 47546

**Comment by HeidiRechek** [comment]
new one created. Azure upload sporadic issue #202
