### ISSUE TITLE
Azure upload sporadic issue

### ISSUE THREAD

**Issue by HeidiRechek** [jenkinsci/azure-storage-plugin#202]
Jenkins and plugins versions report:

Azure Artifact Manager pluginJenkins Azure artifact manager plugin | 94.vcb8b76839313
Azure CLI PluginThis plugin is a sample to explain how to write a Jenkins plugin. | 0.9 
Azure Commons PluginCommon APIs for Azure related Jenkins plugins | 1.1.3 
Azure CredentialsManage Azure credentials using Jenkins Credentials API | 198.vf9c2fdfde55c
Azure SDK API PluginExposes the Azure SDK for Java to other Jenkins plugins. | 61.v6a8af1f5f5b6
Azure Storage pluginAzure Blob Storage Plugin enables uploading build artifacts and downloading blob files from Azure Blob storage. | 362.v15e9c092bf7c

Jenkins latest version. 

Master - Windows Server 2019 (amd64)
Agent - Windows Server 2016 (amd64)

Actual result:
```
here is the log entry from logger://com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher

  log_thrown: com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Failed to validate storage account details. Please verify storage account name and key. If you are using a private or other Azure cloud service, make sure that the blob endpoint url is correct.
	at com.microsoftopentechnologies.windowsazurestorage.helper.AzureUtils.validateStorageAccount(AzureUtils.java:74)
	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.validateData(WAStoragePublisher.java:567)
	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:437)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: reactor.core.Exceptions$ReactiveException: java.io.IOException: An existing connection was forcibly closed by the remote host
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:128)
	at com.azure.storage.blob.BlobContainerClient.existsWithResponse(BlobContainerClient.java:228)
	at com.azure.storage.blob.BlobContainerClient.exists(BlobContainerClient.java:211)
	at com.microsoftopentechnologies.windowsazurestorage.helper.AzureUtils.getBlobContainerReference(AzureUtils.java:127)
	at com.microsoftopentechnologies.windowsazurestorage.helper.AzureUtils.validateStorageAccount(AzureUtils.java:69)
	... 10 more
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 16 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

   message: Failed to validate storage account details. Please verify storage account name and key. If you are using a private or other Azure cloud service, make sure that the blob endpoint url is correct.
   thread_id: 47546


entry from remoting log: 
 R:<blobname>.blob.core.windows.net/20.150.20.132:443] The connection observed an error
java.io.IOException: An existing connection was forcibly closed by the remote host
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by timja** [comment]
how are you uploading? Can you provide a sample that fails?

**Comment by timja** [comment]
I'll take a look when I can, the example above shows blob storage which wasn't touched in this release.
