### ISSUE TITLE
Error to upload files to Azure blob storage

### ISSUE THREAD

**Issue by italoveloso89** [jenkinsci/azure-storage-plugin#209]
### Version report

Jenkins and plugins versions report:

Jenkins version: 2.303.3

Azure AD Plugin - 185.v3b416408dcb1
Azure Artifact Manager plugin - 97.v074e1332e88d
Azure CLI Plugin - 0.9
Azure Credentials - 198.vf9c2fdfde55c
Azure SDK API Plugin - 70.v63f6a95999a7
Azure Storage plugin - 365.vf41653c43b01
Azure VM Agents - 799.va4c741108611

- What Operating System are you using (both controller, and any agents involved in the problem)?
Windows server 2019 (only master)

### Reproduction steps

- Upload large files (1GB +)

- Build config:
`azureUpload blobProperties: [contentLanguage: 'en-US'], containerName: 'testproject', filesPath: '**/Deploy/*.zip, **/Deploy/*.txt', storageCredentialId: 'TestUploadArtifactsAzure', storageType: 'blobstorage', virtualPath: '${P4_CHANGELIST}'`

### Results

Expected result:

Upload files to Azure blob storage

Actual result:

```
14:00:00  java.nio.file.AccessDeniedException: F:\P4\SampleAutomation\DeEscalationXR\Deploy\Android-Development-29967.zip
14:00:00  	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
14:00:00  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
14:00:00  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
14:00:00  	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
14:00:00  	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
14:00:00  	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
14:00:00  	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
14:00:00  	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
14:00:00  	at hudson.FilePath.newInputStreamDenyingSymlinkAsNeeded(FilePath.java:2127)
14:00:00  	at hudson.FilePath.read(FilePath.java:2112)
14:00:00  	at hudson.FilePath.read(FilePath.java:2104)
14:00:00  	at com.microsoftopentechnologies.windowsazurestorage.AzureBlobProperties.detectContentType(AzureBlobProperties.java:120)
14:00:00  	at com.microsoftopentechnologies.windowsazurestorage.AzureBlobProperties.configure(AzureBlobProperties.java:107)
14:00:00  	at com.microsoftopentechnologies.windowsazurestorage.service.UploadToBlobService.configureBlobProperties(UploadToBlobService.java:155)
14:00:00  	at com.microsoftopentechnologies.windowsazurestorage.service.UploadToBlobService.uploadIndividuals(UploadToBlobService.java:125)
14:00:00  Caused: com.microsoftopentechnologies.windowsazurestorage.exceptions.WAStorageException: Fail to upload individual files to blob
14:00:00  	at com.microsoftopentechnologies.windowsazurestorage.service.UploadToBlobService.uploadIndividuals(UploadToBlobService.java:138)
14:00:00  	at com.microsoftopentechnologies.windowsazurestorage.service.UploadService.execute(UploadService.java:545)
14:00:00  	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:472)
14:00:00  Caused: java.io.IOException: AzureStorage - Error occurred while uploading to Azure - lumetobuilds
14:00:00  	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:502)
14:00:00  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
14:00:00  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
14:00:00  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
14:00:00  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
14:00:00  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
14:00:00  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
14:00:00  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
14:00:00  	at java.base/java.lang.Thread.run(Thread.java:834)
14:00:00  Finished: FAILURE
```

**Comment by italoveloso89** [comment]
Hi guys, is there any idea why is it not uploading large zip files?
small files like .txt, .exe upload easily, no problem.

**Comment by JonathanKayumbo** [comment]
Facing the same issue , anyone having  solution or alternative ?

**Comment by timja** [comment]
If you can provide a reproduce-able case from scratch e.g. a pipeline I can take a look.

IIRC last I checked this I couldn't reproduce

**Comment by JonathanKayumbo** [comment]
> If you can provide a reproduce-able case from scratch e.g. a pipeline I can take a look.
> 
> IIRC last I checked this I couldn't reproduce

Okay, great
So below is example pipeline , seems like a file that is less than certain size works but larger file does not work 

`

pipeline {
    agent {
        node {
            label 'u20'
            customWorkspace "${BRANCH_NAME}"
        }
    }
    options {
        skipDefaultCheckout()
        timeout(time: 25, unit: 'MINUTES')
    }
    stages {
       
        stage ("Checkout & Stash") {
            parallel {
                stage ("ub20"){
                    agent {
                        node {
                            label 'u16'
                            customWorkspace "${BRANCH_NAME}"
                        }
                    }
                    steps {
                        script {
                            def containerName = "testcontainer"
                            sh "mkdir testdir"
                            def ArtifactoryServerURL = 'https://artifactoryserver:433/artifactory'
                            def download_list = [
                                "toolchains/arm/ARMCompiler/1.16/ARMCompiler01.tar.gz", // size = 186MB
                                "toolchains/arm/ARMCompiler/6.16/ARMCompiler02.tar.gz", // size = 286MB

                                ]
                            for (item in download_list){
                                withCredentials([string(credentialsId: 'artifactory-apikey', variable: 'ARTIFACTORY_API_KEY')]) {

                                sh """
                                 (curl -sSf -H 'X-jfrog-Art-Api:${ARTIFACTORY_API_KEY}' -O -k '${ArtifactoryServerURL}/${item}')
                                """  
                                }
                            }
                            sh "ls"
                           
                            // Should work (azure-artifact-manager
                            stash name: "SmallSize_zipfile", includes:"ARMCompiler01.tar.gz"
                            azureUpload containerName: containerName, filesPath: 'ARMCompiler01.tar.gz', verbose: true, uploadZips: true

                            stash name: "LargeSize_zipfile", includes:"ARMCompiler02.tar.gz"
                            azureUpload containerName: containerName, filesPath: 'ARMCompiler02.tar.gz', verbose: ture , uploadZips: true
                           

                        }
                    }

                }
            }
        }
    }
    post {
        always {
            script {
                print("\n\nStash timings \n\n")
            }
        }
    }
}
`


I also found this[ link](https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-Block-Blobs--Append-Blobs--and-Page-Blobs?redirectedfrom=MSDN) while trying to understand the max file size of azure blob block on add API call , maybe has something to do with this issue

Thanks for you time

**Comment by timja** [comment]
Can you provide a self contained example that doesn't require your artifactory.

generating a file with `dd` or something like random string utils?

(verifying that it works to reproduce the issue for you?)

**Comment by JonathanKayumbo** [comment]
I think I understand now why upload of a large file does not work, the reason is the API blob put request as per the Azure storage account version I'm using only support a chunky file size of 256MB ( ANY FILE SIZE BELOW 256MB works )

According to that [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-Block-Blobs--Append-Blobs--and-Page-Blobs?redirectedfrom=MSDN), the newer version will support up to 5000MBi 

Thank you for you help though

**Comment by timja** [comment]
> Storage clients default to a 128 MiB maximum single blob upload, settable in the Azure Storage client library for .NET version 11 by using the [SingleBlobUploadThresholdInBytes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobrequestoptions.singleblobuploadthresholdinbytes) property of the [BlobRequestOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobrequestoptions) object. When a block blob upload is larger than the value in this property, storage clients break the file into blocks. You can set the number of threads used to upload the blocks in parallel on a per-request basis using the [ParallelOperationThreadCount](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobrequestoptions.paralleloperationthreadcount) property of the [BlobRequestOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobrequestoptions) object.

It certainly works for bigger, I've been able to upload files of up to 1gb before.

**Comment by erwinzeiter** [comment]
For us using this version helped: Azure Storage Version 365.vf41653c43b01
